# Index {.unnumbered}

A

analysis of microdata 191

analytically interesting microdata set 95

analytically valid microdata set 95

a-priori file 147

assessment (example of risk) 108, 109

attribute disclosure 7

audit 141

authorizations 124

automated tabular data protection 136

B

backtracking 138

backtracking procedure 134

C

categorical data 53, 78

cell costs 134

cell suppression 113

CENEX 5

CIS *See* Community Innovation Survey

clerical pair 47

coalition of respondents 120

Code of Practice 15

column relation 128

Community Innovation Survey 108

comparison of contingency tables 99

concentration rules 119

confidentiality checks 192

consumer finances 87

continuous data 52

controlled remote data processing 191

controlled rounding 161, 177, 183

controlled tabular adjustment 130

controlled teleprocessing 191

correlation matrix 96

cost function 135

covariance matrix 96

CPLEX 153

CTA 130

D

(n,k)-dominance rule 118

data distortion by probability distribution 81

data swapping 56

data usage contract 195

data use 95

datalaboratories 22

data-oriented microaggregation 73

direct comparison of categorical values 99

disclosure 7

disclosure risk 46, 47, 51, 78

disclosure scenario (example of) 107, 109

distance-based record linkage 46

E

EM algorithm 47

Entropy-based measures 100

ethical code 14

ethics 14

European Statistics Code of Practice 15

Eurostat 14

explanatory variable 132

External Archive (EA) 35

external disclosure 137

F

false linkage 47

false negative 47

false positive 47

false unlinkage 47

feasibility interval 127

fixed vs variable group size 73

foreign trade rule 124

frequency table 8, 79, 161

G

GHMITER 156

global 134

global recoding 60, 104

group attribute disclosure 165, 171, 180

H

Hansen-Mukherjee's optimal univariate microaggregation 75

hierarchical file 41, 43

hierarchical stuctures 146

hierarchical table 133

hill-climbing optimization heuristic 91

HiTaS 138

holdings 124

household risk 41

Hybrid data 87

hybrid masking 90

Hyper0 138

Hypercube 138

hypercube method 156

I

identification 162

identifier 51

identifying variable 32

identity disclosure 7, 46

individual attribute disclosure 163, 165, 169

individual ranking 74

inferential disclosure 141

information loss 161, 180

information loss in microdata protection 95

information loss measures for categorical data 99

information loss measures for continuous data 96

insider knowledge 130

intruder 32, 113, 116, 117

intruder scenarios 116

IPSO (Information Preserving Statistical Obfuscation 84

IPSO preserving B and Σ 86

IPSO preserving B 85

IPSO procedure 84

IPSO to get entirely synthetic microdata 87

ISI Declaration on Professional Ethics 14

K

key 32

key variable 51

L

Labour Force Survey 107

lamda (λ)‑parameter 143

lamda-transformation 136

laws 19

LFS *See* Labour Force Survey

linear programming solvers 153

linear relation 127

linear relationship 127

linked tables 146

linked tables 133

Lissy 189

local suppression 61, 104

LP-solver 138

M

Magnitude table 8

manual procedures 137

masking by correlated noise addition 65

masking by noise addition and linear transformations 66

masking by noise addition and nonlinear transformations 67

masking by uncorrelated noise addition 65

masking original data 30, 52

MASSC 58

match 46

matrix masking 53

MDAV heuristic for multivariate microaggregation 75

mean absolute error 97

mean square error 97

mean variation 97

MFR *See* Research use file

microaggregation 56

Microaggregation-based hybrid data 89

microdata 8, 78, 79, 81

microdata for researchers 104

microdata protection 7

microdata protection methods 51

microdata set 51

minimum frequency range' 128

minimum frequency rule 118

minimum protection standards 136

model-based disclosure protection 87

modular 138, 154

multiply-imputed, partially synthetic datasets 87

Muralidhar-Sarathy hybrid generator 87

μ−ARGUS 33, 39, 60, 102, 104

N

negative contributions 123

negative values 148

network flows 155

noise addition 54, 64

nominal scales 53

non-confidential outcome variable 51

non-perturbative masking 52, 59

nosy neighbour scenario 35

O

on-site 80

optimal approach 151

optimal k-partition 69

optimal solution to the microaggregation 74

ordinal scales 53

other partially synthetic and hybrid microdata approaches 87

other record linkage methods 48

output table 193

overview of concepts and methods 51

P

(p,q)-rule 122

p%-rule 118

partial suppression 130

partially synthetic data by Cholesky decomposition 84

partially synthetic microdata 87

periodical data 148

perturbative masking 30, 52, 53

population-uniques 39

post-masking optimization 91

PRAM 58, 78, 100

PRAM-matrix 78, 79

primary confidentiality 192

primary suppression 118

prior‑posterior (*p,q*)%‑rule 122

probabilistic record linkage 47

program 191

program design 192

Pros and cons of synthetic and hybrid microdata 91

protection level 128, 129

protection of output 7

public register 35

public use file 22, 105

PUF *See* Public use file

Q

quasi-identifier 51

R

RADL 189

rank swapping 56

ratios 132

record linkage 46

re-identification-rate 40

remote access 23, 189

remote data processing 191

remote execution 23, 80, 189

resampling 58

research centres 188

research data centre 191

research use file 22

response variable 132

risk and utility 8

risk assessment (example of) 108, 109

rounding 57, 161, 171, 174

row relation 128

R-U confidentiality map 8

S

safety bounds 128

safety rules 116, 117

Sample of Anonymized Records 45

sampling 60

sampling weights 124

SAR 45

SAS 191

scenario (example of disclosure) 107, 109

scientific community 191

secondary cell suppression problem 130

secondary confidentiality 192

sensitive 118

sensitive cells 116

sensitivity measures 117

sensitivity of variables 117

sensitivity rules 117

shadow variables 144

singleton 130, 153, 155

singleton and multi cell disclosure 129

singleton disclosure 137

special uniques 45

splitting approach 145

spontaneous recognition 35

Spontaneous recognition 28

SPSS 191

STATA 191

statistical disclosure control 8

sub-table 133

summary on noise addition 67

suppression pattern 136

synthetic data 30, 52

synthetic data by bootstrap 83

synthetic data by Latin Hypercube Sampling 83

synthetic data by multiple imputation 82

synthetic microdata 81

T

table redesign 143, 171

table specification 132

tabular data protection 6

teleprocessing 191

threshold 38

threshold setting 41

threshold setting for the household risk 42

threshold-rule 104

top and bottom coding 61

transition probability 78, 79, 80

 τ‑ARGUS 115, 130, 131, 136, 143, 151, 161, 182, 183

U

uniques in the population 38

unprojected data 74

unsafe 118

upper and lower protection levels' 128

user analyses 51

W

waivers 123

within-groups sum of squares 69

X

XPRESS 153

[^1]: When *X* has *K* categories and *Y* has *L* categories, the 2-dimensional frequency table **T***~XY~* is a *K × L* matrix.

[^2]: The European Union Labour Force Survey (EU LFS)^?^ is conducted in the 25 Member States of the European Union and 3 countries of the European Free Trade Association (EFTA) in accordance with Council Regulation (EEC) No. 577/98 of 9 March 98; [[http://epp.eurostat.ec.europa.eu/portal/page?\_pageid=1913,47567825,1913_47568351&\_dad=portal&\_schema=PORTAL]{.underline}](http://epp.eurostat.ec.europa.eu/portal/page?_pageid=1913,47567825,1913_47568351&_dad=portal&_schema=PORTAL)

[^3]: [[http://epp.eurostat.ec.europa.eu/cache/ITY_OFFPUB/KS-CC-06-007/EN/KS-CC-06-007-EN.PDF]{.underline}](http://epp.eurostat.ec.europa.eu/cache/ITY_OFFPUB/KS-CC-06-007/EN/KS-CC-06-007-EN.PDF)

[^4]: Some of the main observed variables are in the CIS3 are : principal economic activity, geographical information, number of employees in 1998 and 2000, turnover in 1998 and 2000, exports in 1998 and 2000, gross investment in tangible goods: 2000, number of valid patents at end of 2000, number of employees with higher education (in line with the number of employees in 2000), expenditure in intramural RD (in line with the turnover in 2000), expenditure in extramural RD (in line with the turnover in 2000), expenditure in acquisition of machinery (in line with the turnover in 2000), expenditure in other external knowledge (in line with the turnover in 2000), expenditure in training, market (in line with the turnover in 2000), total innovation expenditure (in line with the turnover in 2000), number of persons involved in intra RD (in line with the number of employees in 2000).

[^5]: $X - x_{n} - \text{.}\text{.}\text{.} - x_{2} - x_{1} < p/\text{100}x_{1}$ for the case of coalitions of *n*-1 respondents, where *n*\>2

[^6]: (Geurts, 1992, Table 10, p 20)

[^7]: One of the secondary cell suppression methods of t-ARGUS, the hypercube method, uses an elaborate internal weighting scheme in order to avoid to some extent the suppression of totals and subtotals which is essential for the performance of the method. In order to avoid that this internal weighting scheme is thrown out of balance, it has been decided to make the cost function facilities of t-ARGUS inoperational for this method.

[^8]: Consider for instance the table of example 3 in section 4.2.2 . Without additional knowledge the bounds for cell (1,1) are $\left( X _ { 11 } ^ { \min } \right)$ = 3 and $X _ { 11 } ^ { \max }$ = 6 . However, if cell (1,2) were a singleton-cell (a cell with a single contributor only) then this single contributor could of course exactly compute the cell value of cell (1,1) by subtracting her own contribution from the row total of row 1.

[^9]: The main persons involved in developing the rules for program design as part of the ad-hoc working group on "confidentiality and documentation" of the research data centres of the Federation and the Länder are: Heike Habla, Jörg Höhne, Ricarda Nauenburg, Ramona Pohl, Dr. Heinz Stralla, and Alexander Vogel. The chapter was written by Andrea Harausz and Ricarda Nauenburg

