## Introduction

This chapter discusses disclosure controls for frequency tables, that is tables of counts (or percentages) where each cell value represents the number of respondents in that cell.

Traditionally frequency tables have been the main method of dissemination for census and social data by NSIs. These tables contain counts of people or households with certain social characteristics. Frequency tables are also used for business data where characteristics are counted, such as the number of businesses. Because of their longer history there has been relatively more research on protecting frequency tables, as compared with newer output methods such as microdata.

Section 5.2 of the chapter outlines the common types of disclosure risk and how the consideration of these risks leads to the definition of unsafe cells in frequency tables. The process of aggregating individual records into groups to display in tables reduces the risk of disclosure compared with microdata, but usually some additional SDC protection is needed for unsafe cells in tables. Disclosure control methods are used to reduce the disclosure risk by disguising these unsafe cells. A range of different SDC methods are described in Section 5.3. A well established method of SDC for frequency tables is rounding and section 5.4 discusses alternative techniques such as conventional and random rounding, small cell adjustment, and controlled rounding. Controlled rounding is currently the recommended method to protect frequency tables. Section 5.5 describes different information loss measures that can be used to evaluate the impact that different disclosure control methods have on the utility of frequency tables. The final section of the chapter, Section 5.6, provides information on the software package τ‑ARGUS and how it can be used to protect frequency tables

