## Rounding

Rounding involves adjusting the values in all cells in a table to a specified base so as to create uncertainty about the real value for any cell. It adds a small, but acceptable, amount of distortion to the original data. Rounding is considered to be an effective method for protecting frequency tables, especially when there are many tables produced from one dataset. It provides protection to small frequencies and zero values (e.g. empty cells). The method is simple to implement, and for the user it is easy to understand as the data is visibly perturbed.

Care must be taken when combining rounded tables to create user-defined areas. Cells can be significantly altered by the rounding process and aggregation compounds these rounding differences. Furthermore, the level of association between variables is affected by rounding, and the variance of the cell counts is increased.

There are several alternative rounding methods including; conventional rounding, random rounding, controlled rounding, and semi-controlled rounding, which are outlined below. Each method is flexible in terms of the choice of the base for rounding, although common choices are 3 and 5. All rounded values (other than zeros) will then be integer multiples of 3 or 5, respectively.

When using conventional rounding, each cell is rounded to the nearest multiple of the base. The marginal totals and table totals are rounded independently from the internal cells. An example of conventional rounding is provided below; @tbl-counts-sex-area shows counts of males and females in different areas, while @tbl-counts-sex-area-round shows the same information rounded to a base of 5.


|        	| **Male** 	| **Female** 	| **Total** 	|
|--------	|:--------:	|:----------:	|:---------:	|
| Area A 	|     1    	|      0     	|     1     	|
| Area B 	|     3    	|      3     	|     6     	|
| Area C 	|    12    	|     20     	|     32    	|
| Total  	|    16    	|     23     	|     39    	|

: Population counts by sex {#tbl-counts-sex-area}


|        	| **Male** 	| **Female** 	| **Total** 	|
|--------	|:--------:	|:----------:	|:---------:	|
| Area A 	|     0    	|      0     	|     0     	|
| Area B 	|     5    	|      5     	|     5     	|
| Area C 	|    10    	|     20     	|     35    	|
| Total  	|    15    	|     25     	|     40    	|

: Population counts by sex (conventional rounding) {#tbl-counts-sex-area-round}

The example shows the Males unsafe cell in Area A in @tbl-counts-sex-area is protected by the rounding process in @tbl-counts-sex-area-round.

The advantages of this method are that the table totals are rounded independently from the internal cells, and therefore consistent table totals will exist within the rounding base. Cells in different tables which represent the same records will always be the same. While this method does provide some confidentiality protection, it is considered less effective than controlled or random rounding. Tables are not additive (e.g. row 3 of Table 5.17 does not sum to 35) and the level of information is poor if there are many values of 1 and 2. The method is not suitable for flexible table generation as it can be easily 'unpicked' when differencing and linking tables. For these reasons conventional rounding is not recommended as a disclosure control method for frequency tables. Conventional rounding is sometimes used by NSIs for quality reasons (e.g. rounding data from small sample surveys to emphasize the uncertain nature of the data). The distinction between rounding performed for disclosure control reasons and rounding performed for quality reasons should always be made clear to users.

Random rounding shifts each cell to one of the two nearest base values in a random manner. Each cell value is rounded independently of other cells, and has a greater probability of being rounded to the nearest multiple of the rounding base. For example, with a base of 5, cell values of 6, 7, 8, or 9 could be rounded to either 5 or 10. Marginal totals are typically rounded separately from the internal cells of the table (i.e. they are not created by adding rounding cell counts) and this means tables are not necessarily additive. Various probability schemes are possible, but an important characteristic is that they should be unbiased. This means there should be no net tendency to round up or down and the average difference from the original counts should be zero.

If we are rounding to base 3 the residual of the cell value after dividing by 3 can be either 0, 1 or 2.

-   If the residual is zero no change is made to the original cell value.

-   If the residual is 1, then with a probability of $2/3$ the cell value is rounded down to the lower multiple of 3 and with a probability of $1/3$ the cell value is rounded up to the higher multiple of 3.

-   If the residual is 2, the probabilities are $2/3$ to round up and $1/3$ to round down.

  --------------------------- -------------------------------------------
  Original Value              Rounded Value (probability)

  0                           0 ($1$)

  1                           0 ($2/3$) or 3 ($1/3$)

  2                           3($2/3$) or 0($1/3$)

  3                           3 ($1$)

  4                           3($2/3$) or 6($1/3$)

  5                           6($2/3$) or 4($1/3$)

  6                           6 ($1$)
  --------------------------- -------------------------------------------

As an example, @tbl-counts-sex-round shows a possible solution for @tbl-counts-sex-area using random rounding to base 5.

  ----------- ---------------------- -------------------------- -----------
              **Male**               **Female**                 **Total**

  Area A      0                      0                          0

  Area B      5                      0                          5

  Area C      10                     20                         35

  Total       15                     20                         40
  ----------- ---------------------- -------------------------- -----------

: Population counts by sex (with random rounding) {#tbl-counts-sex-round}

The main advantages of random rounding are that it is relatively easy to implement, it is unbiased, and it is clear and transparent to users. Table totals are consistent within the rounding base because the totals are rounded independently from the internal cells. All values of 1 and 2 are removed from the table by rounding, which prevents cases of perceived disclosure as well as actual disclosure. The method may also provide some protection against disclosure by differencing as rounding should obscure most of the exact differences between tables.

However, random rounding has disadvantages including the increased information loss which results from the fact that all cells (even safe cells) are rounded. In some instances the protection can be 'unpicked' and in order to ensure adequate protection, the resulting rounded tables need to be audited. Although the method is unbiased, after applying random rounding there may be inconsistencies in data within tables (e.g. rows or columns which do not add up like row 3 of @tbl-counts-sex-round does not sum to 35) and between tables (e.g. the same cell may be rounded to a different number in different tables).

Unlike other rounding methods, controlled rounding yields additive rounded tables. It is the statistical disclosure control method that is generally most effective for frequency tables. The method uses linear programming techniques to round cell values up or down by small amounts, and its strength over other methods is that additivity is maintained in the rounded table, (i.e. it ensures that the rounded values add up to the rounded totals and sub-totals shown in the table). This property not only permits the release of realistic tables which are as close as possible to the original table, but it also makes it impossible to reduce the protection by 'unpicking' the original values by exploiting the differences in the sums of the rounded values. Another useful feature is that controlled rounding can achieve specified levels of protection. In other words, the user can specify the degree of ambiguity added to the cells, for example, they may not want a rounded value within 10% of the true value. Controlled rounding can be used to protect flexible tables although the time taken to implement the method may make it unsuitable for this purpose.

@tbl-counts-sex-control-round shows a possible rounding solution for @tbl-counts-sex-area, using controlled rounding to base 5.

  ----------- ---------------------- -------------------------- -----------
              **Male**               **Female**                 **Total**

  Area A      5                      0                          5

  Area B      0                      5                          5

  Area C      10                     20                         30

  Total       15                     25                         40
  ----------- ---------------------- -------------------------- -----------

: Population counts by sex (controlled rounding) {#tbl-counts-sex-control-round}

The disadvantages of controlled rounding are that it is a complicated method to implement, and it has difficulty coping with the size, scope and magnitude of the census tabular outputs. It is hard to find control-rounded solutions for sets of linked tables, and in order to find a solution cells may be rounded beyond the nearest rounding base. In this case users will know less about exactly how the table was rounded and it is also likely to result in differing values for the same internal cells across different tables.

Semi-controlled rounding also uses linear programming to round table entries up or down but in this case it controls for the overall total in the table, or it controls for each separate output area total. Other marginal and sub totals will not necessarily be additive. This ensures that either the overall total of the table is preserved (or the output area totals are all preserved), and the utility of this method is increased compared with conventional and random rounding. Consistent totals are provided across linked tables, and therefore the method can be used to protect flexible tables, although the time it takes to implement may make it unsuitable. Disadvantages of semi-controlled rounding relate to the fact that tables are not fully additive, and finding an optimal solution can prove difficult.

  ---------------------------------------------------------------- --------------------------- ----------------------------------------------------- -------------------------------------------------
                                                                   **Conventional Rounding**   **Controlled (and semi-controlled) Rounding**         **Random rounding**

  Internal cells add to table totals (additvity)                   No                          Yes                                                   No

  Method provides enough SDC protection (and cannot be unpicked)   No                          Yes                                                   In some situations this method can be unpicked.

  Method is quick and easy to implement                            Yes                         It can take time for this method to find a solution   Yes
  ---------------------------------------------------------------- --------------------------- ----------------------------------------------------- -------------------------------------------------

: Summary of SDC rounding methods {#tbl-summary-rounding-methods}

There are some more specialised rounding methods which have been used at various times by NSIs to protect census data, two of these methods are described below.

Small cell adjustment was used (in addition to random swapping (a pre-tabular method)) to protect 2001 Census tabular outputs for England, Wales and Northern Ireland. This method was also used by the ABS to protect their tabular outputs from the 2001 Census.

Applying small cell adjustments involves randomly adjusting small cells within tables upwards or downwards to a base using an unbiased prescribed probability scheme. During the process:

-   small counts appearing in a table cells are adjusted

-   totals and sub totals are calculated as the sum of the adjusted counts. This means all tables are internally additive.

-   tables are independently adjusted so counts of the same population which appear in two different tables, may not necessarily have the same value.

-   tables for higher geographical levels are independently adjusted, and therefore will not necessarily be the sum of the lower component geographical units.

-   output is produced from one database which has been adjusted for estimated undercount so the tables produced from this one database provide a consistent picture of this one population.

Advantages of this method are that tables are additive, and the elimination of small cells in the table removes cases of perceived as well as actual identity disclosure. In addition, loss of information is lower for standard tables as all other cells remain the same, however information loss will be high for sparse tables. Other disadvantages include inconsistency of margins between linked tables since margins are calculated using perturbed internal cells, and this increases the risk of tables being unpicked. Furthermore, this method provides little protection against disclosure by differencing, and is not suitable for flexible table generation.

Barnardisation is a form of cell perturbation which modifies each internal cell of every table by +1, 0 or -1, according to probabilities. Zeros are not adjusted. The method offers some protection against disclosure by differencing, however table totals are added up from the perturbed internal cells, resulting in inconsistent totals between tables. Typically, the probability p is quite small and therefore a high proportion of risky cells are not modified. The exact proportion of cells modified is not revealed to the user. This is generally a difficult method to implement for flexible output.

